import React from 'react';
import LogoSrcTag from '../static/img/logo.svg';
// import LogoSrcTag from '../static/img/logo.svg';
import BannerSrc from '../static/img/banner/banner-3.jpg';
import HeartSrc from '../static/img/icon/heart.png';
import CompareSrc from '../static/img/icon/compare.png';
import SearchSrc from '../static/img/icon/search.png';
import ProdSaleSrc from '../static/img/product-sale.png';
import Hero1Src from '../static/img/hero/hero-2.jpg';
import Hero2Src from '../static/img/hero/hero-3.jpg';
import VladPhotoSrc from '../static/img/about/team-11.jpg';
import BogdanPhotoSrc from '../static/img/about/team-22.jpg';
import DmytroPhotoSrc from '../static/img/about/team-44.jpg';
import RomanPhotoSrc from '../static/img/about/team-33.jpg';

import AboutBGSrc from '../static/img/about/aboutus_bg.jpg';
import TestimonialAuthorSrc from '../static/img/about/testimonial-author.jpg';

export const LogoSrcIcon = (props?: any) => <LogoSrcTag height="2em" {...props} />;
export const BannerSrcIcon = (props?: any) => <img src={BannerSrc} alt="Banner" {...props} />;
export const HeartSrcIcon = (props?: any) => <img src={HeartSrc} alt="Heart" {...props} />;
export const CompareSrcIcon = (props?: any) => <img src={CompareSrc} alt="Compare" {...props} />;
export const SearchSrcIcon = (props?: any) => <img src={SearchSrc} alt="Search" {...props} />;
export const ProdSaleSrcIcon = (props?: any) => <img src={ProdSaleSrc} alt="ProdSale" {...props} />;
export const AboutBGSrcIcon = (props?: any) => <img src={AboutBGSrc} alt="AboutBG" {...props} />;
export const Hero1SrcIcon = Hero1Src;
export const Hero2SrcIcon = Hero2Src;
export const VladPhotoSrcIcon = (props?: any) => <img src={VladPhotoSrc} alt="VladPhoto" {...props} />;
export const BogdanPhotoSrcIcon = (props?: any) => <img src={BogdanPhotoSrc} alt="BogdanPhoto" {...props} />;
export const DmytroPhotoSrcIcon = (props?: any) => <img src={DmytroPhotoSrc} alt="DmytroPhoto" {...props} />;
export const RomanPhotoSrcIcon = (props?: any) => <img src={RomanPhotoSrc} alt="RomanPhoto" {...props} />;
export const TestimonialAuthorSrcIcon = (props?: any) => <img src={TestimonialAuthorSrc} alt="TestimonialAuthor" {...props} />;
